// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4SblyUMKlZxEFPgG-hu6b3kDrOuW-bxw',
    appId: '1:287661326372:web:4677bf44e1927e1b5958b1',
    messagingSenderId: '287661326372',
    projectId: 'aplicativo-de-filmes-26f39',
    authDomain: 'aplicativo-de-filmes-26f39.firebaseapp.com',
    storageBucket: 'aplicativo-de-filmes-26f39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHjNWfc7FwZgu_w6Womq9splKzcaprDdM',
    appId: '1:287661326372:android:8f14bff16e37f5ae5958b1',
    messagingSenderId: '287661326372',
    projectId: 'aplicativo-de-filmes-26f39',
    storageBucket: 'aplicativo-de-filmes-26f39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMstAyRcvmGitom-Km-KRSAUzXgLy7g8Y',
    appId: '1:287661326372:ios:8a369f939770ae1f5958b1',
    messagingSenderId: '287661326372',
    projectId: 'aplicativo-de-filmes-26f39',
    storageBucket: 'aplicativo-de-filmes-26f39.appspot.com',
    iosBundleId: 'com.example.trabalho1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMstAyRcvmGitom-Km-KRSAUzXgLy7g8Y',
    appId: '1:287661326372:ios:8a369f939770ae1f5958b1',
    messagingSenderId: '287661326372',
    projectId: 'aplicativo-de-filmes-26f39',
    storageBucket: 'aplicativo-de-filmes-26f39.appspot.com',
    iosBundleId: 'com.example.trabalho1',
  );
}
